name: Labeler
on:
  pull-request:
    branches: main, develop

jobs:
  label:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"